### PR TITLE
chore(*): update changelog.md

### PR DESCRIPTION
**Pull request by simon-cj**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
Update changelog.md

**Which issue(s) this PR is related to** *(optional, link to 3rd issue(s))*:

Fixes #

Reference to #

**Special notes for your reviewer**:

/cc @FogDong @judgeeeeee 

**Does this PR introduce a user-facing change?**:

```release-note
Update changelog.md
```

### CODE REVIEW

**Comment by FogDong** [comment]
Please add the release note.

**Comment by simon-cj** [comment]
> Please add the release note.

done

**Review by FogDong — COMMENTED** [review]
/lgtm

**Comment by FogDong** [comment]
Maybe we could merge this PR first and use the release note tools later, WDYT /cc @judgeeeeee

**Comment by gaocegege** [comment]
I am closing it since it is outdated.

**Pull request closed without merging**
