### PR TITLE
Migrate to distribution/reference

### LINKED ISSUE #209: [Bug] Save/Tag interpret numeric tags as port numbers
**Is this a BUG REPORT or FEATURE REQUEST?**: Bug Report

/kind bug

**What happened**:

`ormb save . foo:1`

This creates a model `foo:1` with tag `latest`, which is not a valid OCI ref.

**What you expected to happen**:

A new model, with repository `foo` and tag `1` to be created

**How to reproduce it (as minimally and precisely as possible)**:

```bash
$ ormb save . foo:1
ref:       foo:1:latest
digest:    4f4fb700ef54461cfa02571ae0db9a0dc1e0cdb5577484a6d75e68dc38e8acc1
size:      32B
format:    Others
latest: saved
```

Compare with
```bash
$ docker build -t foo:1 .
...
Successfully tagged foo:1
```

**Anything else we need to know?**:

Appears to be improper handling of port numbers in the registry component of the ref, e.g. `ormb save . local.host:8080/foo:1` works as expected.

```
$ ormb version
Version: 0.1.0-rc.2
Git SHA: ede0dc0c04a7d6386c0d1f6b6e8e5d361a5df2f0
Repo Root: git@github.com:gaocegege/ormb.git
Go Version: go1.17.2
Go OS/Arch: linux/amd64
```

### PR DESCRIPTION
**Pull request by sel**
**What type of PR is this?**

/kind bug
/area cli

**What this PR does / why we need it**:

Use the tried and tested package github.com/docker/distribution/reference for parsing OCI references.

**Which issue(s) this PR is related to**:

Fixes #209

**Special notes for your reviewer**:

- This patch uses the already-vendored package [github.com/docker/distribution/reference](https://github.com/kleveross/ormb/tree/master/vendor/github.com/docker/distribution/reference). When the dependencies are upgraded we should switch to the CNCF-contributed package, which was factored out of the docker one and keeps the same API: [github.com/distribution/reference ](https://github.com/distribution/reference)

- I chose to keep the existing `Reference` API in ormb's `oci` package as a facade instead of updating all call-sites to use github.com/docker/distribution/reference. If you prefer I am open to doing the latter also.

- The distribution/reference package has [extensive tests](https://github.com/distribution/reference/blob/main/reference_test.go) so I only added a few here to regression-test the specific bug fixed by this change.

/cc @gaocegege

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by gaocegege — APPROVED** [review]
LGTM :+1:
/lgtm

**Comment by markhulia** [comment]
@gaocegege could you please merge this PR?

**Comment by gaocegege** [comment]
CI blocks the automatic merge. I am merging it manually.

**Comment by sel** [comment]
@gaocegege could you please make a new release in GitHub? The `ormb` binary in the Python SDK is outdated.

**Pull request merged**
