### PR TITLE
chore: add default tag when tag is empty

### PR DESCRIPTION
**Pull request by whalecold**
**What this PR does / why we need it**:

Add your description

**Which issue(s) this PR is related to** *(optional, link to 3rd issue(s))*:

Fixes #

Reference to #

**Special notes for your reviewer**:

/cc @gaocegege 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by whalecold** [comment]
docker will use `latest` tag when the provided tag is empty.

**Review by gaocegege — COMMENTED** [review]
Maybe we also need to support it in save and push.

**Comment by whalecold** [comment]
> Maybe we also need to support it in save and push.

Done, I moved it to the `ParseReference` function, that can unifies all kinds operator.

**Review by gaocegege — COMMENTED** [review]
/lgtm

Thanks for your contribution! :tada: :+1:

**Pull request merged**
